CREATE TABLE IF NOT EXISTS driftsavvik
(
    driftsavvik_id      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    palop_id            integer REFERENCES palop,
    tidspunkt_fra       timestamp NOT NULL,
    tidspunkt_til       timestamp,
    opprettet_av        text,
    arsak               text,
    opprettet_tidspunkt timestamp DEFAULT current_timestamp
);

CREATE INDEX driftsavvik_palop_id_index ON driftsavvik (palop_id);
CREATE INDEX driftsavvik_tidspunkt_til_index ON driftsavvik (tidspunkt_til);