name: bidrag-reskontro
ingresses:
  - https://bidrag-reskontro.intern.nav.no
limits:
  memory: 1024Mi
requests:
  cpu: 200m
  memory: 512Mi
replicas:
  max: 2
  min: 2

maskinporten:
  url: https://maskinporten.no
env:
  SKATT_URL: https://ske-elin-api-bisysresk.elin.innkreving.skatteetaten.no
  SKATT_HOST: ske-elin-api-bisysresk.elin.innkreving.skatteetaten.no
  MASKINPORTEN_SCOPES: "skatteetaten:barnebidragreskontro"
  RESKONTRO_LEGACY_URL: https://bidrag-reskontro-legacy.prod-fss-pub.nais.io
  RESKONTRO_LEGACY_SCOPE: prod-fss.bidrag.bidrag-reskontro-legacy
  RESKONTRO_LEGACY_HOST: bidrag-reskontro-legacy.prod-fss-pub.nais.io
  RESKONTRO_LEGACY_ENABLED: false
  JAVA_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0
azure:
  inbound:
    rules:
      - application: bisys
        namespace: bidrag
        cluster: prod-fss
      - application: bidrag-dokument-bestilling
        namespace: bidrag
        cluster: prod-gcp
      - application: bidrag-regnskap
        namespace: bidrag
        cluster: prod-gcp