name: bidrag-reskontro
ingresses:
  - https://bidrag-reskontro.intern.nav.no
maskinporten:
  url: https://maskinporten.no
env:
  SKATT_URL: https://bidrag-stubs.intern.dev.nav.no #TODO()
  SKATT_HOST: bidrag-stubs.intern.dev.nav.no #TODO()
  MASKINPORTEN_SCOPES: "nav:bidrag/v1/bidragskrav"
  JAVA_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0