name: bidrag-reskontro
ingresses:
  - https://bidrag-reskontro.intern.nav.no
maskinporten:
  url: https://maskinporten.no
env:
  SKATT_URL: https://bidrag-elin-stub.intern.dev.nav.no #TODO()
  SKATT_HOST: bidrag-elin-stub.intern.dev.nav.no #TODO()
  MASKINPORTEN_SCOPES: "nav:bidrag/v1/bidragskrav" #TODO()
  RESKONTRO_LEGACY_URL: https://bidrag-reskontro-legacy.intern.nav.no
  RESKONTRO_LEGACY_SCOPE: prod-fss.bidrag.bidrag-reskontro-legacy
  RESKONTRO_LEGACY_ENABLED: true
  JAVA_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0
azure:
  inbound:
    rules:
      - application: bisys
        namespace: bidrag
        cluster: prod-fss