name: bidrag-reskontro
ingresses:
  - https://bidrag-reskontro.intern.nav.no
limits:
  memory: 1024Mi
requests:
  cpu: 50m
  memory: 206Mi
replicas:
  max: 2
  min: 2

maskinporten:
  url: https://maskinporten.no
env:
  SKATT_URL: https://bidrag-elin-stub.intern.dev.nav.no #TODO()
  SKATT_HOST: bidrag-elin-stub.intern.dev.nav.no #TODO()
  MASKINPORTEN_SCOPES: "nav:bidrag/v1/bidragskrav" #TODO()
  RESKONTRO_LEGACY_URL: https://bidrag-reskontro-legacy.prod-fss-pub.nais.io
  RESKONTRO_LEGACY_SCOPE: prod-fss.bidrag.bidrag-reskontro-legacy
  RESKONTRO_LEGACY_HOST: bidrag-reskontro-legacy.prod-fss-pub.nais.io
  RESKONTRO_LEGACY_ENABLED: true
  JAVA_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0
azure:
  inbound:
    rules:
      - application: bisys
        namespace: bidrag
        cluster: prod-fss