CREATE TABLE IF NOT EXISTS palop
(
    palop_id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    kjoredato           timestamp NOT NULL,
    fullfort_tidspunkt  timestamp,
    for_periode         text      NOT NULL,
    opprettet_tidspunkt timestamp DEFAULT current_timestamp,
    CONSTRAINT for_periode_unique UNIQUE (for_periode)
);

CREATE INDEX for_periode_index ON palop (for_periode);
CREATE INDEX fullfort_tidspunkt_index ON palop (fullfort_tidspunkt);