CREATE TABLE IF NOT EXISTS konteringer
(
    kontering_id                   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    oppdragsperiode_id             integer REFERENCES oppdragsperioder,
    transaksjonskode               text    NOT NULL,
    overforingsperiode             text    NOT NULL,
    overforingstidspunkt           timestamp,
    behandlingsstatus_ok_tidspunkt timestamp,
    type                           text    NOT NULL,
    soknad_type                    text,
    gebyr_rolle                    text,
    siste_referansekode            text,
    sendt_i_palopsfil              boolean NOT NULL,
    opprettet_tidspunkt            timestamp DEFAULT current_timestamp
);

CREATE INDEX oppdragsperiode_id_index ON konteringer (oppdragsperiode_id);
CREATE INDEX siste_referansekode_index ON konteringer (siste_referansekode);
CREATE INDEX konteringer_overforingstidspunkt_index ON konteringer (overforingstidspunkt);
CREATE INDEX behandlingsstatus_ok_tidspunkt_index ON konteringer (behandlingsstatus_ok_tidspunkt);
