CREATE TABLE IF NOT EXISTS oppdrag
(
    oppdrag_id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1),
    stonad_type         text NOT NULL,
    sak_id              text NOT NULL,
    kravhaver_ident     text,
    skyldner_ident      text NOT NULL,
    utsatt_til_dato     date,
    endret_tidspunkt    timestamp,
    opprettet_tidspunkt timestamp DEFAULT current_timestamp
);

CREATE INDEX endret_tidspunkt_index ON oppdrag (endret_tidspunkt);
CREATE INDEX unike_identifikatorer_index ON oppdrag (stonad_type, kravhaver_ident, skyldner_ident, sak_id);