apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: {{ database.navn }}
        type: POSTGRES_15
        diskSize: {{ database.size }}
        tier: {{ database.tier }}
        databases:
        - name: bidrag-aktoerregister-db
          envVarPrefix: DB
  liveness:
    path: /actuator/health/liveness
    initialDelay: 120
    timeout: 10
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health/readiness
    initialDelay: 120
    timeout: 10
    periodSeconds: 5
    failureThreshold: 10
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 1024Mi
  replicas:
    cpuThresholdPercentage: 50
    min: 2
  kafka:
    pool: {{ kafka.pool }}
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "aktoerregister.read"
          enabled: true
          product: "bidrag"
          allowedIntegrations:
            - maskinporten
          atMaxAge: 120
          consumers:
            - name: "NAV"
              orgno: "889640782"
            - name: "Skatteetaten"
              orgno: "974761076"
  envFrom:
    - secret: bidrag-aktoerregister-mqpassword
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
  accessPolicy:
    outbound:
      external:
        - host: {{ env.BIDRAG_PERSON_HOST }}
        - host: {{ env.BIDRAG_SAMHANDLER_HOST }}
