apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  secureLogs:
    enabled: true
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 30
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 30
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: {{limits.cpu}}
      memory: {{limits.memory}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
  replicas:
    disableAutoScaling: true
    max: {{replicas.max}}
    min: {{replicas.min}}
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  accessPolicy:
    inbound:
      rules:
      {{#each azure.inbound.rules}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{this.cluster}}
      {{/each}}
  webproxy: true
