name: Deploy Q1 aktoerregister
on:
  workflow_dispatch:
  schedule:
      - cron : '0 2 * * 1'
  push:
    branches:
      - 'q1/**'
      - 'Q1/**'
    paths:
      - '.nais/bidrag-aktoerregister/**.yaml'
      - '.github/workflows/aktoerregister_deploy_q1.yaml'
      - 'pom.xml'
      - '**/bidrag-aktoerregister/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to Q1"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      maven_options: -B -q -fae -f bidrag-aktoerregister
      ktlint_options: -f bidrag-aktoerregister
      docker_context: ./bidrag-aktoerregister
      nais_variabler_filnavn: bidrag-aktoerregister/q1.yaml
      nais_hovedfil_navn: bidrag-aktoerregister/nais.yaml
      image_suffix: bidrag-aktoerregister
      tag: bidrag-aktoerregister