name: Deploy Q2 aktoerregister
on:
  push:
    branches:
      - 'q2/**'
      - 'Q2/**'
    paths:
      - '.nais/bidrag-aktoerregister/**.yaml'
      - '.github/workflows/aktoerregister_deploy_q2.yaml'
      - 'pom.xml'
      - '**/bidrag-aktoerregister/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to Q2"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      maven_options: -B -q -fae -f bidrag-aktoerregister
      ktlint_options: -f bidrag-aktoerregister
      dockerfile_with_path: ./bidrag-aktoerregister/Dockerfile
      docker_context: ./bidrag-aktoerregister
      nais_variabler_filnavn: bidrag-aktoerregister/q2.yaml
      nais_hovedfil_navn: bidrag-aktoerregister/nais.yaml
      image_suffix: bidrag-aktoerregister
      tag: bidrag-aktoerregister