name: Dependabot - bygg og test
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'pom.xml'
      - 'apps/**/pom.xml'
      - '.github/dependabot.yml'

jobs:
  bygg_og_test:
    if: github.actor == 'dependabot[bot]'
    name: "Bygg og test alle moduler"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: |
            [
              {
                "id": "github",
                "username": "x-access-token",
                "password": "${{ secrets.READER_TOKEN }}"
              },
              {
                "id": "github2",
                "username": "x-access-token",
                "password": "${{ secrets.READER_TOKEN }}"
              }
            ]
      - name: Bygg og kjør tester for hele reactoren (inkl. ktlint og IT)
        run: mvn -B -fae verify -Pit
