name: Deploy feature
on:
  push:
    branches:
      - '**'
      - '!main'
      - '!dependabot/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Finner hvilke moduler det har vært endringer i
      - name: Identifiserer endrede moduler
        id: changed_modules
        run: |
          changed_modules=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^bidrag-skatteetaten/' | cut -d/ -f2 | uniq)
          echo "::set-output name=modules::$changed_modules"

      # Bygger modulene det har vært endringer i
      - name: Bygg endrede moduler
        run: |
          modules="${{ steps.changed_modules.outputs.modules }}"
          for module in $modules; do
            echo "Building and deploying modul: $module"
            name: "Build and deploy to feature"
            permissions:
              contents: "read"
              id-token: "write"
            uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
            secrets: inherit
            with:
              maven_options: -B -q -fae -Pit -f $module
              nais_variabler_filnavn: feature-$module.yaml
          done
        if: steps.changed_modules.outputs.modules != ''

      # Bygger alle moduler om ingen endringer blir oppdaget
      - name: Build all modules
        run: mvn clean install test -B -e -fae -Pit -f pom.xml
        if: steps.changed_modules.outputs.modules == ''
