name: Deploy elin-stub
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - '.nais/bidrag-elin-stub/**.yaml'
      - '.github/workflows/elin-stub_deploy.yaml'
      - 'pom.xml'
      - '**/bidrag-elin-stub/**'

jobs:
  build_and_deploy:
    name: "Build and deploy"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      maven_options: -B -q -fae -f bidrag-elin-stub
      ktlint_options: -f bidrag-elin-stub
      dockerfile_with_path: ./bidrag-elin-stub/Dockerfile
      docker_context: ./bidrag-elin-stub
      nais_variabler_filnavn: bidrag-elin-stub/main.yaml
      nais_hovedfil_navn: bidrag-elin-stub/nais.yaml
      image_suffix: bidrag-elin-stub
