name: Deploy Q4 regnskap
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches:
      - '**'
      - '!main'
      - '!q1/**'
      - '!Q1/**'
      - '!q2/**'
      - '!Q2/**'
    paths:
      - '.nais/bidrag-regnskap/**.yaml'
      - '.github/workflows/regnskap_deploy_q4.yaml'
      - 'pom.xml'
      - '**/bidrag-regnskap/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to Q4"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      maven_options: -B -q -fae -Pit -f bidrag-regnskap
      maven_test_lifecycle: verify
      ktlint_options: -f bidrag-regnskap
      dockerfile_with_path: ./bidrag-regnskap/Dockerfile
      docker_context: ./bidrag-regnskap
      nais_variabler_filnavn: bidrag-regnskap/q4.yaml
      nais_hovedfil_navn: bidrag-regnskap/nais.yaml
      image_suffix: bidrag-regnskap
      tag: bidrag-regnskap