name: Deploy feature regnskap
on:
  push:
    branches:
      - '**'
      - '!main'
      - '!dependabot/**'
    paths:
      - '!bidrag-aktoerregister/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to feature"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      maven_options: -B -q -fae -Pit -f bidrag-regnskap
      maven_test_lifecycle: verify
      ktlint_options: -f bidrag-regnskap
      dockerfile_with_path: ./bidrag-regnskap/Dockerfile
      docker_context: ./bidrag-regnskap
