name: Deploy main regnskap
on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - '.nais/bidrag-regnskap/**.yaml'
      - '.github/workflows/regnskap_deploy_main.yaml'
      - 'pom.xml'
      - '**/bidrag-regnskap/**'

jobs:
  build:
    name: "Build"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/build.yaml@feature/splitte-bygg-og-deploy
    secrets: inherit
    with:
      maven_options: -B -q -fae -Pit -f bidrag-regnskap
      maven_test_lifecycle: verify
      ktlint_options: -f bidrag-regnskap
      dockerfile_with_path: ./bidrag-regnskap/Dockerfile
      docker_context: ./bidrag-regnskap
      image_suffix: bidrag-regnskap
      tag: bidrag-regnskap

  deploy_q1:
    name: "Deploy til Q1"
    needs: build
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@feature/splitte-bygg-og-deploy
    secrets: inherit
    with:
      docker_image: ${{ needs.build.outputs.docker_image }}
      nais_hovedfil_navn: bidrag-regnskap/nais.yaml
      nais_variabler_filnavn: bidrag-regnskap/main.yaml

  deploy_q2:
    name: "Deploy til Q2"
    needs: build
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@feature/splitte-bygg-og-deploy
    secrets: inherit
    with:
      docker_image: ${{ needs.build.outputs.docker_image }}
      nais_hovedfil_navn: bidrag-regnskap/nais.yaml
      nais_variabler_filnavn: bidrag-regnskap/q2.yaml

