name: Deploy main regnskap
on:
  pull_request:
    types: [ ready_for_review, opened, synchronize ]
    paths-ignore:
      - '**/bidrag-aktoerregister/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to main"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      maven_options: -B -q -fae -Pit -f bidrag-regnskap
      maven_test_lifecycle: verify
      ktlint_options: -f bidrag-regnskap
      dockerfile_with_path: ./bidrag-regnskap/Dockerfile
      docker_context: ./bidrag-regnskap
      nais_variabler_filnavn: bidrag-regnskap/main.yaml
      nais_hovedfil_navn: bidrag-regnskap/nais.yaml
      image_suffix: bidrag-regnskap
