name: Deploy prod regnskap
on:
  push:
    branches:
      - 'main'
    paths:
      - '.nais/bidrag-regnskap/**.yaml'
      - '.github/workflows/regnskap_deploy_prod.yaml'
      - 'pom.xml'
      - '**/bidrag-regnskap/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to prod"
    permissions:
      contents: "write"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy_prod.yaml@main
    secrets: inherit
    with:
      maven_options: -B -q -fae -Pit -f bidrag-regnskap
      ktlint_options: -f bidrag-regnskap
      docker_context: ./bidrag-regnskap
      nais_variabler_filnavn: bidrag-regnskap/prod.yaml
      nais_hovedfil_navn: bidrag-regnskap/nais.yaml
      image_suffix: bidrag-regnskap
      tag: bidrag-regnskap