name: Deploy prod reskontro
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/bidrag-aktoerregister/**'
      - '**/bidrag-regnskap/**'
      - '**/bidrag-elin-stub/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to prod"
    permissions:
      contents: "write"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy_prod.yaml@main
    secrets: inherit
    with:
      maven_options: -B -q -fae -f bidrag-reskontro
      ktlint_options: -f bidrag-reskontro
      dockerfile_with_path: ./bidrag-reskontro/Dockerfile
      docker_context: ./bidrag-reskontro
      nais_variabler_filnavn: bidrag-reskontro/prod.yaml
      nais_hovedfil_navn: bidrag-reskontro/nais.yaml
      image_suffix: bidrag-reskontro
